on:
  push:

name: test

jobs:
  test-arc:
    strategy:
      matrix:
        name: [ test1 , test2, test3 ]
    name: ${{ matrix.name }}
    runs-on: k8s-small-staging-new
    services:
      postgresql:
        image: public.ecr.aws/bitnami/postgresql:latest
        env:
          POSTGRESQL_DATABASE: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
    container: ubuntu
    steps:
    - run: echo "Hello, world!"
    - uses: azure/setup-kubectl@v3
      id: install
    - run: kubectl version || true
    - run: nc -v postgresql 5432 || true
